/**
 * Общие константы приложения
 */
export const MAX_NOTIFICATIONS = 50

/**
 * Единый источник всех ключей localStorage
 */
export const STORAGE_KEYS = {
  USERS: 'fastfingers_users',
  CURRENT_USER: 'fastfingers_current_user',
  USER: 'fastfingers_user',
  HISTORY: 'fastfingers_history',
  NOTIFICATIONS: 'fastfingers_notifications',
  ADMIN_TEXTS: 'fastfingers_admin_texts',
  PENDING_SESSIONS: 'fastfingers_pending_sessions',
  CLOUD_SYNC: 'fastfingers_cloud_sync',
  BACKEND_STATUS: 'fastfingers_backend_status',
  RESET_TOKENS: 'fastfingers_reset_tokens',
  LOGIN_ATTEMPTS: 'fastfingers_login_attempts',
  TEXT_USAGE: 'fastfingers_textUsage',
  ADAPTIVE_DIFFICULTY: 'fastfingers_adaptive_difficulty',
  AUTOSAVE: 'fastfingers-autosave',
  SETTINGS: 'fastfingers-settings',
  PROGRESS: 'fastfingers-progress',
  CHALLENGES: 'fastfingers_challenges',
  CHALLENGE_PROGRESS: 'fastfingers_challenge_progress',
  STREAK: 'fastfingers_streak',
  COMPLETIONS: 'fastfingers_challenge_completions',
  NOTIF_SOUND: 'fastfingers_notif_sound',
  NOTIF_LEVELUP: 'fastfingers_notif_levelup',
  NOTIF_ACHIEVEMENT: 'fastfingers_notif_achievement',
  ONBOARDING: 'fastfingers_onboarding_seen',
  DUELS_PLAYED: 'fastfingers_duelsPlayed',
  TOURNAMENTS_PLAYED: 'fastfingers_tournamentsPlayed',
  DAILY_CHALLENGES_COMPLETED: 'fastfingers_dailyChallengesCompleted',
  USED_GAME_MODES: 'fastfingers_usedGameModes',
  ACHIEVEMENTS: 'fastfingers_achievements',
  GOALS: 'fastfingers_goals',
  THEME: 'fastfingers_theme',
  THEME_OPTION: 'fastfingers_theme_option',
  FONT_SIZE: 'fastfingers_font_size',
  CUSTOM_COLORS: 'fastfingers_custom_colors',
  CONTRAST: 'fastfingers_contrast',
  MUSIC_GENRE: 'fastfingers_music_genre',
  MUSIC_TEMPO: 'fastfingers_music_tempo',
  MUSIC_VOLUME: 'fastfingers_music_volume',
  MUSIC_KEY: 'fastfingers_music_key',
  SESSION_TIMER: 'fastfingers_session_timer',
  PWA_DISMISSED: 'fastfingers_pwa_dismissed',
  LOCAL_BACKUP: 'fastfingers_local_backup',
  CUSTOM_EXERCISES: 'fastfingers_custom_exercises',
  COOKIE_CONSENT: 'fastfingers_cookie_consent',
  LANGUAGE: 'fastfingers_language',
  LEARNING_PROGRESS: 'fastfingers_learning_progress',
} as const
