export type LessonLayout = 'jcuken' | 'qwerty' | 'dvorak'

export interface Lesson {
  id: number
  title: string
  description: string
  text: string
  difficulty: number
  focusKeys: string[]
  minWpm: number
  minAccuracy: number
  unlocked: boolean
  layout: LessonLayout
}

export const lessons: Lesson[] = [
  // ==================== JCUKEN (Russian) ====================
  // Уровень 1: Основной ряд
  {
    id: 1,
    title: 'Основной ряд - левая рука',
    description: 'Изучаем клавиши а, в, ы, п',
    text: 'аааа вввв ыыыы пппп авып пыав вапы ыпав авып пыав вапы ыпав',
    difficulty: 1,
    focusKeys: ['а', 'в', 'ы', 'п'],
    minWpm: 10,
    minAccuracy: 90,
    unlocked: true,
    layout: 'jcuken',
  },
  {
    id: 2,
    title: 'Основной ряд - правая рука',
    description: 'Изучаем клавиши о, р, л, д',
    text: 'оооо рррр лллл дддд орлд лдоро ролд дорл орлд лдоро ролд дорл',
    difficulty: 1,
    focusKeys: ['о', 'р', 'л', 'д'],
    minWpm: 10,
    minAccuracy: 90,
    unlocked: false,
    layout: 'jcuken',
  },
  {
    id: 3,
    title: 'Основной ряд - вместе',
    description: 'Объединяем обе руки',
    text: 'авып орлд авып орлд выап лдро паыв длро выап лдро паыв длро',
    difficulty: 2,
    focusKeys: ['а', 'в', 'ы', 'п', 'о', 'р', 'л', 'д'],
    minWpm: 15,
    minAccuracy: 90,
    unlocked: false,
    layout: 'jcuken',
  },
  {
    id: 4,
    title: 'Простые слова',
    description: 'Первые слова из основного ряда',
    text: 'папа мама рама лава лапа право слово дело рука голова',
    difficulty: 2,
    focusKeys: ['а', 'в', 'ы', 'п', 'о', 'р', 'л', 'д'],
    minWpm: 15,
    minAccuracy: 85,
    unlocked: false,
    layout: 'jcuken',
  },

  // Уровень 2: Верхний ряд
  {
    id: 5,
    title: 'Верхний ряд - левая рука',
    description: 'Изучаем клавиши й, ц, у, к, е',
    text: 'йййй цццц уууу кккк ееее йцуке екуйц укейц йцуке екуйц',
    difficulty: 3,
    focusKeys: ['й', 'ц', 'у', 'к', 'е'],
    minWpm: 20,
    minAccuracy: 85,
    unlocked: false,
    layout: 'jcuken',
  },
  {
    id: 6,
    title: 'Верхний ряд - правая рука',
    description: 'Изучаем клавиши н, г, ш, щ, з',
    text: 'нннн гггг шшшщ щщщз зззз нгшщз зщшгн шщнгз нгшщз зщшгн',
    difficulty: 3,
    focusKeys: ['н', 'г', 'ш', 'щ', 'з'],
    minWpm: 20,
    minAccuracy: 85,
    unlocked: false,
    layout: 'jcuken',
  },
  {
    id: 7,
    title: 'Верхний и основной ряд',
    description: 'Комбинируем ряды',
    text: 'йцуке нгшщз авып орлд йцуке нгшщз авып орлд йцуке нгшщз',
    difficulty: 4,
    focusKeys: ['й', 'ц', 'у', 'к', 'е', 'н', 'г', 'ш', 'щ', 'з'],
    minWpm: 25,
    minAccuracy: 85,
    unlocked: false,
    layout: 'jcuken',
  },
  {
    id: 8,
    title: 'Слова с верхним рядом',
    description: 'Практика на словах',
    text: 'кот урок рука книга наука школа улица цветок дерево',
    difficulty: 4,
    focusKeys: ['й', 'ц', 'у', 'к', 'е', 'н', 'г', 'ш', 'щ', 'з'],
    minWpm: 25,
    minAccuracy: 85,
    unlocked: false,
    layout: 'jcuken',
  },

  // Уровень 3: Нижний ряд
  {
    id: 9,
    title: 'Нижний ряд - левая рука',
    description: 'Изучаем клавиши я, ч, с, м, и',
    text: 'яяяя чччч сссс мммм ииии ячсми имсчая ячсми имсчая',
    difficulty: 5,
    focusKeys: ['я', 'ч', 'с', 'м', 'и'],
    minWpm: 30,
    minAccuracy: 85,
    unlocked: false,
    layout: 'jcuken',
  },
  {
    id: 10,
    title: 'Нижний ряд - правая рука',
    description: 'Изучаем клавиши т, ь, б, ю',
    text: 'тттт ьььь бббб юююю тьбюю юбьтт тьюбь тьбюю юбьтт',
    difficulty: 5,
    focusKeys: ['т', 'ь', 'б', 'ю'],
    minWpm: 30,
    minAccuracy: 85,
    unlocked: false,
    layout: 'jcuken',
  },
  {
    id: 11,
    title: 'Все три ряда',
    description: 'Полная клавиатура',
    text: 'йцуке нгшщз авып орлд ячсми тьбюъ йцуке нгшщз авып орлд',
    difficulty: 6,
    focusKeys: ['й', 'ц', 'у', 'к', 'е', 'н', 'г', 'ш', 'щ', 'з', 'х', 'ъ'],
    minWpm: 35,
    minAccuracy: 85,
    unlocked: false,
    layout: 'jcuken',
  },

  // Уровень 4: Предложения
  {
    id: 12,
    title: 'Простые предложения',
    description: 'Печатаем предложения',
    text: 'На дворе трава. На траве дрова. Не руби дрова на траве двора.',
    difficulty: 6,
    focusKeys: [],
    minWpm: 35,
    minAccuracy: 90,
    unlocked: false,
    layout: 'jcuken',
  },
  {
    id: 13,
    title: 'Сложные предложения',
    description: 'Длинные предложения',
    text: 'Съешь ещё этих мягких французских булок, да выпей чаю.',
    difficulty: 7,
    focusKeys: [],
    minWpm: 40,
    minAccuracy: 90,
    unlocked: false,
    layout: 'jcuken',
  },
  {
    id: 14,
    title: 'Панграммы',
    description: 'Все буквы алфавита',
    text: 'В чащах юга жил бы цитрус? Да, но фальшивый экземпляр!',
    difficulty: 7,
    focusKeys: [],
    minWpm: 40,
    minAccuracy: 90,
    unlocked: false,
    layout: 'jcuken',
  },

  // Уровень 5: Продвинутый
  {
    id: 15,
    title: 'Технические термины',
    description: 'Слова из IT сферы',
    text: 'компьютер программа интернет браузер сервер файл документ система',
    difficulty: 8,
    focusKeys: [],
    minWpm: 45,
    minAccuracy: 90,
    unlocked: false,
    layout: 'jcuken',
  },
  {
    id: 16,
    title: 'Программный код',
    description: 'Печатаем код',
    text: 'const hello = "world"; function greet(name) { return `Hello, ${name}!`; }',
    difficulty: 8,
    focusKeys: [],
    minWpm: 45,
    minAccuracy: 90,
    unlocked: false,
    layout: 'jcuken',
  },
  {
    id: 17,
    title: 'Типы данных TypeScript',
    description: 'Код с типами',
    text: 'interface User { id: number; name: string; email: string; } type Status = "active" | "inactive";',
    difficulty: 9,
    focusKeys: [],
    minWpm: 50,
    minAccuracy: 90,
    unlocked: false,
    layout: 'jcuken',
  },

  // Уровень 6: Мастер
  {
    id: 18,
    title: 'Сложные панграммы',
    description: 'Максимальная сложность',
    text: 'Широкая электрификация южных губерний даст мощный толчок подъёму сельского хозяйства.',
    difficulty: 9,
    focusKeys: [],
    minWpm: 55,
    minAccuracy: 92,
    unlocked: false,
    layout: 'jcuken',
  },
  {
    id: 19,
    title: 'Литературный текст',
    description: 'Отрывок из произведения',
    text: 'В начале июля, в чрезвычайно жаркое время, под вечер, один молодой человек вышел из своей каморки, которую нанимал от жильцов в С-м переулке.',
    difficulty: 10,
    focusKeys: [],
    minWpm: 60,
    minAccuracy: 92,
    unlocked: false,
    layout: 'jcuken',
  },
  {
    id: 20,
    title: 'Финальный экзамен',
    description: 'Проверка всех навыков',
    text: 'Съешь ещё этих мягких французских булок, да выпей чаю. В чащах юга жил бы цитрус? Да, но фальшивый экземпляр! Широкая электрификация южных губерний даст мощный толчок подъёму сельского хозяйства.',
    difficulty: 10,
    focusKeys: [],
    minWpm: 60,
    minAccuracy: 95,
    unlocked: false,
    layout: 'jcuken',
  },

  // ==================== QWERTY (English) ====================
  // Level 1: Home Row
  {
    id: 101,
    title: 'Home Row - Left Hand',
    description: 'Learn keys A, S, D, F',
    text: 'aaaa ssss dddd ffff asdf fdsa asdf fdsa asdf fdsa asdf fdsa',
    difficulty: 1,
    focusKeys: ['a', 's', 'd', 'f'],
    minWpm: 10,
    minAccuracy: 90,
    unlocked: true,
    layout: 'qwerty',
  },
  {
    id: 102,
    title: 'Home Row - Right Hand',
    description: 'Learn keys J, K, L, ;',
    text: 'jjjj kkkk llll ;;;; jkl; ;lkj jkl; ;lkj jkl; ;lkj',
    difficulty: 1,
    focusKeys: ['j', 'k', 'l', ';'],
    minWpm: 10,
    minAccuracy: 90,
    unlocked: false,
    layout: 'qwerty',
  },
  {
    id: 103,
    title: 'Home Row - Both Hands',
    description: 'Combine both hands on home row',
    text: 'asdf jkl; asdf jkl; fdsa ;lkj asdf jkl; fdsa ;lkj',
    difficulty: 2,
    focusKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
    minWpm: 15,
    minAccuracy: 90,
    unlocked: false,
    layout: 'qwerty',
  },
  {
    id: 104,
    title: 'Simple Words',
    description: 'First words from home row keys',
    text: 'dad lad sad fall flask ask dad lad ask salad flask',
    difficulty: 2,
    focusKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l'],
    minWpm: 15,
    minAccuracy: 85,
    unlocked: false,
    layout: 'qwerty',
  },

  // Level 2: Top Row
  {
    id: 105,
    title: 'Top Row - Left Hand',
    description: 'Learn keys Q, W, E, R, T',
    text: 'qqqq wwww eeee rrrr tttt qwert trewq qwert trewq',
    difficulty: 3,
    focusKeys: ['q', 'w', 'e', 'r', 't'],
    minWpm: 20,
    minAccuracy: 85,
    unlocked: false,
    layout: 'qwerty',
  },
  {
    id: 106,
    title: 'Top Row - Right Hand',
    description: 'Learn keys Y, U, I, O, P',
    text: 'yyyy uuuu iiii oooo pppp youip poiuy youip poiuy',
    difficulty: 3,
    focusKeys: ['y', 'u', 'i', 'o', 'p'],
    minWpm: 20,
    minAccuracy: 85,
    unlocked: false,
    layout: 'qwerty',
  },
  {
    id: 107,
    title: 'Top + Home Row',
    description: 'Combine top and home rows',
    text: 'qwerty uiop asdf jkl; qwerty uiop asdf jkl; qwerty',
    difficulty: 4,
    focusKeys: ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
    minWpm: 25,
    minAccuracy: 85,
    unlocked: false,
    layout: 'qwerty',
  },
  {
    id: 108,
    title: 'Words with Top Row',
    description: 'Practice with real words',
    text: 'the quick write route power your tree water quite outer',
    difficulty: 4,
    focusKeys: ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
    minWpm: 25,
    minAccuracy: 85,
    unlocked: false,
    layout: 'qwerty',
  },

  // Level 3: Bottom Row
  {
    id: 109,
    title: 'Bottom Row - Left Hand',
    description: 'Learn keys Z, X, C, V, B',
    text: 'zzzz xxxx cccc vvvv bbbb zxcvb bvcxz zxcvb bvcxz',
    difficulty: 5,
    focusKeys: ['z', 'x', 'c', 'v', 'b'],
    minWpm: 30,
    minAccuracy: 85,
    unlocked: false,
    layout: 'qwerty',
  },
  {
    id: 110,
    title: 'Bottom Row - Right Hand',
    description: 'Learn keys N, M, comma, period, slash',
    text: 'nnnn mmmm ,,,, .... //// nm,. /.,mn nm,. /.,mn',
    difficulty: 5,
    focusKeys: ['n', 'm', ',', '.', '/'],
    minWpm: 30,
    minAccuracy: 85,
    unlocked: false,
    layout: 'qwerty',
  },
  {
    id: 111,
    title: 'All Three Rows',
    description: 'Full keyboard practice',
    text: 'the quick brown fox jumps over the lazy dog',
    difficulty: 6,
    focusKeys: ['z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/'],
    minWpm: 35,
    minAccuracy: 85,
    unlocked: false,
    layout: 'qwerty',
  },

  // Level 4: Sentences
  {
    id: 112,
    title: 'Simple Sentences',
    description: 'Type full sentences',
    difficulty: 6,
    focusKeys: [],
    text: 'The cat sat on the mat. A dog ran in the park. The sun is bright today.',
    minWpm: 35,
    minAccuracy: 90,
    unlocked: false,
    layout: 'qwerty',
  },
  {
    id: 113,
    title: 'Complex Sentences',
    description: 'Longer sentences with punctuation',
    text: 'The quick brown fox jumps over the lazy dog, and then runs away.',
    difficulty: 7,
    focusKeys: [],
    minWpm: 40,
    minAccuracy: 90,
    unlocked: false,
    layout: 'qwerty',
  },
  {
    id: 114,
    title: 'Pangrams',
    description: 'Sentences with every letter',
    text: 'The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs.',
    difficulty: 7,
    focusKeys: [],
    minWpm: 40,
    minAccuracy: 90,
    unlocked: false,
    layout: 'qwerty',
  },

  // Level 5: Advanced
  {
    id: 115,
    title: 'Technical Terms',
    description: 'IT and tech vocabulary',
    text: 'keyboard monitor internet browser server function variable compile',
    difficulty: 8,
    focusKeys: [],
    minWpm: 45,
    minAccuracy: 90,
    unlocked: false,
    layout: 'qwerty',
  },
  {
    id: 116,
    title: 'Code Practice',
    description: 'Type actual code',
    text: 'const x = 42; const greet = (name: string) => `Hello, ${name}!`; export default greet;',
    difficulty: 8,
    focusKeys: [],
    minWpm: 45,
    minAccuracy: 90,
    unlocked: false,
    layout: 'qwerty',
  },
  {
    id: 117,
    title: 'TypeScript Types',
    description: 'Code with type annotations',
    text: 'type User = { id: number; name: string; }; const users: User[] = [{ id: 1, name: "Alice" }];',
    difficulty: 9,
    focusKeys: [],
    minWpm: 50,
    minAccuracy: 90,
    unlocked: false,
    layout: 'qwerty',
  },

  // Level 6: Master
  {
    id: 118,
    title: 'Complex Pangrams',
    description: 'Maximum difficulty',
    text: 'Sphinx of black quartz, judge my vow. How vexingly quick daft zebras jump!',
    difficulty: 9,
    focusKeys: [],
    minWpm: 55,
    minAccuracy: 92,
    unlocked: false,
    layout: 'qwerty',
  },
  {
    id: 119,
    title: 'Literary Text',
    description: 'A passage from literature',
    text: 'It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness.',
    difficulty: 10,
    focusKeys: [],
    minWpm: 60,
    minAccuracy: 92,
    unlocked: false,
    layout: 'qwerty',
  },
  {
    id: 120,
    title: 'Final Exam',
    description: 'Test all your skills',
    text: 'The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs. Sphinx of black quartz, judge my vow.',
    difficulty: 10,
    focusKeys: [],
    minWpm: 60,
    minAccuracy: 95,
    unlocked: false,
    layout: 'qwerty',
  },

  // ==================== DVORAK (English) ====================
  // Level 1: Home Row
  {
    id: 201,
    title: 'Home Row - Left Hand',
    description: 'Learn keys A, O, E, U',
    text: 'aaaa oooo eeee uuuu aoeu uoea aoeu uoea aoeu uoea',
    difficulty: 1,
    focusKeys: ['a', 'o', 'e', 'u'],
    minWpm: 10,
    minAccuracy: 90,
    unlocked: true,
    layout: 'dvorak',
  },
  {
    id: 202,
    title: 'Home Row - Right Hand',
    description: 'Learn keys H, T, N, S',
    text: 'hhhh tttt nnnn ssss htns snt h htns snt h htns snt h',
    difficulty: 1,
    focusKeys: ['h', 't', 'n', 's'],
    minWpm: 10,
    minAccuracy: 90,
    unlocked: false,
    layout: 'dvorak',
  },
  {
    id: 203,
    title: 'Home Row - Both Hands',
    description: 'Combine both hands on home row',
    text: 'aoeu htns aoeu htns uoea snt h aoeu htns uoea snt h',
    difficulty: 2,
    focusKeys: ['a', 'o', 'e', 'u', 'h', 't', 'n', 's'],
    minWpm: 15,
    minAccuracy: 90,
    unlocked: false,
    layout: 'dvorak',
  },
  {
    id: 204,
    title: 'Simple Words',
    description: 'First words from home row keys',
    text: 'one use out house south tune note seat east aunt',
    difficulty: 2,
    focusKeys: ['a', 'o', 'e', 'u', 'h', 't', 'n', 's'],
    minWpm: 15,
    minAccuracy: 85,
    unlocked: false,
    layout: 'dvorak',
  },

  // Level 2: Top Row
  {
    id: 205,
    title: 'Top Row - Left Hand',
    description: 'Learn keys :, Q, J, K, X',
    text: ':::: qqqq jjjj kkkk xxxx :qjkx xkj q: :qjkx xkj q:',
    difficulty: 3,
    focusKeys: [':', 'q', 'j', 'k', 'x'],
    minWpm: 20,
    minAccuracy: 85,
    unlocked: false,
    layout: 'dvorak',
  },
  {
    id: 206,
    title: 'Top Row - Right Hand',
    description: 'Learn keys P, Y, F, G, C',
    text: 'pppp yyyy ffff gggg cccc pyfgc cgfyp pyfgc cgfyp',
    difficulty: 3,
    focusKeys: ['p', 'y', 'f', 'g', 'c'],
    minWpm: 20,
    minAccuracy: 85,
    unlocked: false,
    layout: 'dvorak',
  },
  {
    id: 207,
    title: 'Top + Home Row',
    description: 'Combine top and home rows',
    text: ':qjkx pyfgc aoeu htns :qjkx pyfgc aoeu htns',
    difficulty: 4,
    focusKeys: [':', 'q', 'j', 'k', 'x', 'p', 'y', 'f', 'g', 'c'],
    minWpm: 25,
    minAccuracy: 85,
    unlocked: false,
    layout: 'dvorak',
  },
  {
    id: 208,
    title: 'Words with Top Row',
    description: 'Practice with real words',
    text: 'quick jump fancy pitch check exact jack type fancy',
    difficulty: 4,
    focusKeys: [':', 'q', 'j', 'k', 'x', 'p', 'y', 'f', 'g', 'c'],
    minWpm: 25,
    minAccuracy: 85,
    unlocked: false,
    layout: 'dvorak',
  },

  // Level 3: Bottom Row
  {
    id: 209,
    title: 'Bottom Row - Left Hand',
    description: 'Learn keys ;, Z, comma, period',
    text: ';;;; zzzz ,,,, .... ;z,. .,;z ;z,. .,;z',
    difficulty: 5,
    focusKeys: [';', 'z', ',', '.'],
    minWpm: 30,
    minAccuracy: 85,
    unlocked: false,
    layout: 'dvorak',
  },
  {
    id: 210,
    title: 'Bottom Row - Right Hand',
    description: 'Learn keys B, R, L, D, W',
    text: 'bbbb rrrr llll dddd wwww brldw wdlrb brldw wdlrb',
    difficulty: 5,
    focusKeys: ['b', 'r', 'l', 'd', 'w'],
    minWpm: 30,
    minAccuracy: 85,
    unlocked: false,
    layout: 'dvorak',
  },
  {
    id: 211,
    title: 'All Three Rows',
    description: 'Full keyboard practice',
    text: 'the quick brown fox jumps over the lazy dog',
    difficulty: 6,
    focusKeys: [';', 'z', ',', '.', 'b', 'r', 'l', 'd', 'w'],
    minWpm: 35,
    minAccuracy: 85,
    unlocked: false,
    layout: 'dvorak',
  },

  // Level 4: Sentences
  {
    id: 212,
    title: 'Simple Sentences',
    description: 'Type full sentences',
    text: 'The cat sat on the mat. A dog ran in the park. The sun is bright today.',
    difficulty: 6,
    focusKeys: [],
    minWpm: 35,
    minAccuracy: 90,
    unlocked: false,
    layout: 'dvorak',
  },
  {
    id: 213,
    title: 'Complex Sentences',
    description: 'Longer sentences with punctuation',
    text: 'The quick brown fox jumps over the lazy dog, and then runs away.',
    difficulty: 7,
    focusKeys: [],
    minWpm: 40,
    minAccuracy: 90,
    unlocked: false,
    layout: 'dvorak',
  },
  {
    id: 214,
    title: 'Pangrams',
    description: 'Sentences with every letter',
    text: 'The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs.',
    difficulty: 7,
    focusKeys: [],
    minWpm: 40,
    minAccuracy: 90,
    unlocked: false,
    layout: 'dvorak',
  },

  // Level 5: Advanced
  {
    id: 215,
    title: 'Technical Terms',
    description: 'IT and tech vocabulary',
    text: 'keyboard monitor internet browser server function variable compile',
    difficulty: 8,
    focusKeys: [],
    minWpm: 45,
    minAccuracy: 90,
    unlocked: false,
    layout: 'dvorak',
  },
  {
    id: 216,
    title: 'Code Practice',
    description: 'Type actual code',
    text: 'const x = 42; const greet = (name: string) => `Hello, ${name}!`; export default greet;',
    difficulty: 8,
    focusKeys: [],
    minWpm: 45,
    minAccuracy: 90,
    unlocked: false,
    layout: 'dvorak',
  },
  {
    id: 217,
    title: 'TypeScript Types',
    description: 'Code with type annotations',
    text: 'type User = { id: number; name: string; }; const users: User[] = [{ id: 1, name: "Alice" }];',
    difficulty: 9,
    focusKeys: [],
    minWpm: 50,
    minAccuracy: 90,
    unlocked: false,
    layout: 'dvorak',
  },

  // Level 6: Master
  {
    id: 218,
    title: 'Complex Pangrams',
    description: 'Maximum difficulty',
    text: 'Sphinx of black quartz, judge my vow. How vexingly quick daft zebras jump!',
    difficulty: 9,
    focusKeys: [],
    minWpm: 55,
    minAccuracy: 92,
    unlocked: false,
    layout: 'dvorak',
  },
  {
    id: 219,
    title: 'Literary Text',
    description: 'A passage from literature',
    text: 'It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness.',
    difficulty: 10,
    focusKeys: [],
    minWpm: 60,
    minAccuracy: 92,
    unlocked: false,
    layout: 'dvorak',
  },
  {
    id: 220,
    title: 'Final Exam',
    description: 'Test all your skills',
    text: 'The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs. Sphinx of black quartz, judge my vow.',
    difficulty: 10,
    focusKeys: [],
    minWpm: 60,
    minAccuracy: 95,
    unlocked: false,
    layout: 'dvorak',
  },
]

// Проверка доступности урока
export function isLessonUnlocked(lessonId: number, completedLessons: number[]): boolean {
  // First lesson of each layout is always unlocked
  if (lessonId === 1 || lessonId === 101 || lessonId === 201) return true

  const prevLesson = lessonId - 1
  return completedLessons.includes(prevLesson)
}

// Проверка завершения урока
export function isLessonCompleted(wpm: number, accuracy: number, lesson: Lesson): boolean {
  return wpm >= lesson.minWpm && accuracy >= lesson.minAccuracy
}
